# Generated by Django 6.0.3 on 2026-04-14 04:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('net_pay_liability_account', models.ForeignKey(limit_choices_to={'account_type': 'liability'}, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_netpay', to='erp.account')),
                ('paye_liability_account', models.ForeignKey(limit_choices_to={'account_type': 'liability'}, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_paye', to='erp.account')),
                ('pension_liability_account', models.ForeignKey(limit_choices_to={'account_type': 'liability'}, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_pension', to='erp.account')),
                ('salaries_expense_account', models.ForeignKey(limit_choices_to={'account_type': 'expense'}, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_salaries', to='erp.account')),
            ],
            options={
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pension_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pension_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='erp.payrollperiod')),
            ],
            options={
                'unique_together': {('payroll_period', 'employee')},
            },
        ),
    ]
