# Generated by Django 6.0.3 on 2026-04-14 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_id']},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='account_number',
            new_name='bank_account',
        ),
        migrations.AddField(
            model_name='employee',
            name='job_position',
            field=models.CharField(choices=[('hod', 'Head of Department'), ('accountant', 'Accountant'), ('craftsman', 'Craftsman'), ('manager', 'Manager'), ('staff', 'Staff'), ('intern', 'Intern')], default='staff', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='pension_pin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
